### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by k4m4h4l** [vndly/botcoin#1]
C:\Users\usuario\Desktop\BINANCE\botcoin-master>npm uninstall
up to date in 0.124s

C:\Users\usuario\Desktop\BINANCE\botcoin-master>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\usuario\Desktop\BINANCE\botcoin-master\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\usuario\Desktop\BINANCE\botcoin-master\package.json'
npm WARN botcoin-master No description
npm WARN botcoin-master No repository field.
npm WARN botcoin-master No README data
npm WARN botcoin-master No license field.

**Comment by mauriciotogneri** [comment]
This is a Java project, not a Javascript one.
